// <auto-generated />
using System;
using LoomAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoomAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230310164914_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("LoomAPI.Models.Erro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerdaEficienciaParadas")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeParadas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempoMedio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoParadas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TearId");

                    b.ToTable("Erros");
                });

            modelBuilder.Entity("LoomAPI.Models.Tear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eficiencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraDeLigacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoDecorrido")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoFinal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoInicial")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoLigado")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoParado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teares");
                });

            modelBuilder.Entity("LoomAPI.Models.Erro", b =>
                {
                    b.HasOne("LoomAPI.Models.Tear", null)
                        .WithMany("Erros")
                        .HasForeignKey("TearId");
                });

            modelBuilder.Entity("LoomAPI.Models.Tear", b =>
                {
                    b.Navigation("Erros");
                });
#pragma warning restore 612, 618
        }
    }
}
